version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.grpc.address=:443
      - --entrypoints.web.address=:80
      - --log.level=INFO
      - --api.insecure=true
    ports:
      - "80:80"    # HTTP
      - "443:443"  # gRPC
      - "8080:8080" # Traefik Dashboard
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./traefik/server.crt:/etc/traefik/server.crt
      - ./traefik/server.key:/etc/traefik/server.key
      - /var/run/docker.sock:/var/run/docker.sock

  krakend:
    image: devopsfaith/krakend:2
    container_name: krakend
    ports:
      - "8081:8080" # KrakenD's exposed port, avoid conflict with Traefik
      - "9090:9090" # Prometheus metrics
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
      - ./traefik/server.crt:/etc/krakend/server.crt
      - ./traefik/server.key:/etc/krakend/server.key
    environment:
      - KRAKEND_DEBUG=1
      - KRAKEND_LOG_LEVEL=DEBUG
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.krakend-router.rule=Host(`krakend.localhost`)"
    - "traefik.http.routers.krakend-router.entrypoints=web"
    - "traefik.http.services.krakend-service.loadbalancer.server.port=8080"

  grpc-apigw:
    build:
      context: .
      dockerfile: ./grpc-apigw/Dockerfile
    container_name: grpc-apigw
    ports:
      - "8082:8082"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.grpc-apigw-router.rule=Host(`grpc-apigw.localhost`)"
    - "traefik.http.routers.grpc-apigw-router.entrypoints=web"
    - "traefik.http.services.grpc-apigw-service.loadbalancer.server.port=8082"

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-router.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.auth-router.entrypoints=grpc"
    expose:
      - "50051" # Exposed only for Traefik routing
    # ports:
      # - "50051:50051"

  user:
    build:
      context: .
      dockerfile: ./user/Dockerfile
    container_name: user
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-router.rule=Host(`user.localhost`)"
      - "traefik.http.routers.user-router.entrypoints=grpc"
    expose:
      - "50052" # Exposed only for Traefik routing
    # ports:
      # - "50052:50052"