http:
  routers:
    auth-router:
      entryPoints:
        - grpc
      service: auth-service
      rule: "Host(`auth.localhost`)"
      tls:
        certResolver: ""

    user-router:
      entryPoints:
        - grpc
      service: user-service
      rule: "Host(`user.localhost`)"
      tls:
        certResolver: ""

    krakend-router:
      entryPoints:
        - web
      service: krakend-service
      rule: "Host(`krakend.localhost`)"
      tls:
        certResolver: ""

    grpc-apigw-router:
      entryPoints:
        - web
      service: grpc-apigw-service
      rule: "Host(`grpc-apigw.localhost`)"
      tls:
        certResolver: ""

  services:
    krakend-service:
      loadBalancer:
        servers:
          - url: http://krakend:8080

    grpc-apigw-service:
      loadBalancer:
        servers:
          - url: http://grpc-apigw:8082

    auth-service:
      loadBalancer:
        servers:
          - url: h2c://auth:50051

    user-service:
      loadBalancer:
        servers:
          - url: h2c://user:50052

tls:
  certificates:
    - certFile: "/etc/traefik/server.crt"
      keyFile: "/etc/traefik/server.key"
