entryPoints:
  grpc:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: arifboyz16@gmail.com
      storage: /etc/traefik/acme.json
      tlsChallenge: {}

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
